import 'package:json_annotation/json_annotation.dart';

part 'aqi_model.g.dart';

/// Represents a single AQI reading row returned by the UrbanPulse backend.
///
/// JSON contract (matches FastAPI `AQIReadingResponse`):
/// ```json
/// {
///   "timestamp": "2026-05-30 14:00:00",
///   "ward":      "Silk Board",
///   "aqi":       142.0,
///   "pm25":      71.0,
///   "congestion": 63.5
/// }
/// ```
@JsonSerializable()
class AqiModel {
  /// ISO-ish datetime string from the backend ("YYYY-MM-DD HH:MM:SS").
  final String timestamp;

  /// Name of the Bangalore ward / monitoring station.
  final String ward;

  /// Air Quality Index — US EPA scale (0–500).
  final double aqi;

  /// PM2.5 fine particulate concentration in µg/m³.
  final double pm25;

  /// Traffic congestion percentage (0–100).
  final double congestion;

  const AqiModel({
    required this.timestamp,
    required this.ward,
    required this.aqi,
    required this.pm25,
    required this.congestion,
  });

  /// Deserialize from JSON — generated by build_runner.
  factory AqiModel.fromJson(Map<String, dynamic> json) =>
      _$AqiModelFromJson(json);

  /// Serialize to JSON — generated by build_runner.
  Map<String, dynamic> toJson() => _$AqiModelToJson(this);

  /// Safely parse the timestamp string into a [DateTime].
  DateTime get parsedTimestamp {
    try {
      // Backend sends "2026-05-30 14:00:00" — replace space with T for ISO 8601
      return DateTime.parse(timestamp.replaceFirst(' ', 'T'));
    } catch (_) {
      return DateTime.now();
    }
  }

  /// Human-readable AQI category label.
  String get aqiCategory {
    if (aqi <= 50) return 'Good';
    if (aqi <= 100) return 'Moderate';
    if (aqi <= 150) return 'Unhealthy (SG)';
    if (aqi <= 200) return 'Unhealthy';
    if (aqi <= 300) return 'Very Unhealthy';
    return 'Hazardous';
  }

  @override
  String toString() =>
      'AqiModel(ward: $ward, aqi: $aqi, timestamp: $timestamp)';
}

/// Lightweight chart data point used by [AqiLineChart] and [CorrelationHeatmap].
class AqiPoint {
  /// The time-axis value for the chart.
  final DateTime time;

  /// The AQI value for the y-axis.
  final double value;

  const AqiPoint({required this.time, required this.value});
}
